<Project>
  <PropertyGroup>
    <!-- MUST be set for Directory.Packages.props to work -->
    <ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>

    <!-- Lock restore for consistency -->
    <RestorePackagesWithLockFile>true</RestorePackagesWithLockFile>
  </PropertyGroup>

  <ItemGroup>
    <!-- Nuget packages ofr unit tests -->
    <PackageVersion Include="Microsoft.NET.Test.Sdk" Version="17.14.1" />
    <PackageVersion Include="xunit" Version="2.9.3" />
    <PackageVersion Include="xunit.runner.visualstudio" Version="3.1.4" />
    <PackageVersion Include="coverlet.collector" Version="6.0.4" />
    <PackageVersion Include="Moq" Version="4.20.72" />
  </ItemGroup>
</Project>
