<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <OutputType>Library</OutputType>
    <RootNamespace>MessagingProvidersDemo.Presentation.MVC</RootNamespace>
    <AssemblyName>Messaging-Providers-Demo.Presentation.MVC</AssemblyName>
    <Deterministic>true</Deterministic>
    <MvcBuildViews>false</MvcBuildViews>
    <Configurations>Debug;Release</Configurations>

    <!-- Optional: centralize build output -->
    <OutputPath>$(SolutionDir)bin\dll\$(Configuration)\</OutputPath>

    <MvcBuildViews>false</MvcBuildViews>
    <UseIISExpress>true</UseIISExpress>
    <Use64BitIISExpress>true</Use64BitIISExpress>
    <IISExpressSSLPort>44364</IISExpressSSLPort>
  </PropertyGroup>

  <!-- Debug / Release settings -->
  <PropertyGroup Condition="'$(Configuration)'=='Debug'">
    <DefineConstants>DEBUG;TRACE</DefineConstants>
    <Optimize>false</Optimize>
    <DebugType>full</DebugType>
    <DebugSymbols>true</DebugSymbols>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)'=='Release'">
    <DefineConstants>TRACE</DefineConstants>
    <Optimize>true</Optimize>
    <DebugType>pdbonly</DebugType>
    <WarningLevel>4</WarningLevel>
  </PropertyGroup>

  <!-- Project references -->
  <ItemGroup>
    <ProjectReference Include="..\Application\Application.csproj" />
    <ProjectReference Include="..\Helpers\Helpers.csproj" />
    <ProjectReference Include="..\Infrastructure\Infrastructure.csproj" />
  </ItemGroup>

  <!-- System references -->
  <ItemGroup>
    <Reference Include="Microsoft.CSharp" />
    <Reference Include="System.Web" />
    <Reference Include="System.Web.Routing" />
    <Reference Include="System.Web.Abstractions" />
    <Reference Include="System.Web.Mvc" />
  </ItemGroup>

  <!-- NuGet packages references -->
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNet.Mvc" />
    <PackageReference Include="Microsoft.AspNet.Razor" />
    <PackageReference Include="Microsoft.AspNet.WebPages" />
    <PackageReference Include="Microsoft.AspNet.Web.Optimization" />
    <PackageReference Include="Newtonsoft.Json" />
    <PackageReference Include="Microsoft.CodeDom.Providers.DotNetCompilerPlatform" />
  </ItemGroup>

</Project>
